services:
  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-net
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:1.0.2
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    ports:
      - "8081:8081"
    networks:
      - backend-net

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    networks:
      - backend-net

  notes-service:
    build:
      context: ./notes-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
      - patient-service
    networks:
      - backend-net

  assessment-service:
    build:
      context: ./assessment-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - mongodb
      - patient-service
      - notes-service
    networks:
      - backend-net

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - patient-service      # attendez que les micro-services soient prêts
      - notes-service
    networks:
      - backend-net

volumes:
  mongo-data:

networks:
  backend-net:
    driver: bridge
