spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: patient-route
          uri: http://patient-service:8082     # pointant sur votre service patient
          predicates:
            - Path=/patients/**
          filters:
            # on enlève /patients et on forwarde le reste à la racine du micro-service
            - RewritePath=/patients/(?<segment>.*), /${segment}

        - id: notes-route
          uri: http://notes-service:8083       # pointant sur votre service notes
          predicates:
            - Path=/notes/**
          filters:
            # idem pour les notes
            - RewritePath=/notes/(?<segment>.*), /${segment}

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
